### ISSUE TITLE
Compiling the gdbserver

### ISSUE THREAD

**Issue by AntonKrug** [embecosm/riscv-gdbserver#3]
Hi,

I'm wondering how to get this gdbserver compiled, when I run the:

`./configure --with-verilator-headers=/usr/local/share/verilator/include CXXFLAGS="-std=gnu++11 -g"            VTESTBENCH=`pwd`/picorv32/scripts/gdbserver/obj_dir`

I get error that the riscv model directory is not specified, but when I try to add them by hand:

`./configure --with-verilator-headers=/usr/local/share/verilator/include --with-picorv32-modeldir=/home/antonkrug/riscv-gdbserver/picorv32/ --with-picorv32-topmodule=/home/antonkrug/riscv-gdbserver/picorv32/            CXXFLAGS="-std=gnu++11 -g"            VTESTBENCH=`pwd`/picorv32/scripts/gdbserver/obj_dir
`
Then I get the following error:

> configure: error: RI5CY model directory not specified

What is the expected way compiling this repo?

Best regards,
Anton

BTW: I would recommend stating in the README:

> git clone http://git@github.com/embecosm/picorv32

instead of the

> git clone ssh://git@github.com/embecosm/picorv32

**Comment by jeremybennett** [comment]
Hi Anton,

Thanks for your input. Sorry for the slow reply - August is holiday time.

The `README` instructions have not kept up with changes to the project. I've fixed this in commit 0x28319cb.
